language: python

matrix:
  include:
    - os: linux
      env:
        - INSTALL_LUA="lua=5.3"
        - LUA="lua"
        - LUA_OS="linux"
    - os: osx
      language: generic
      env:
        - INSTALL_LUA="lua=5.3"
        - LUA="lua"
        - LUA_OS="macosx"

before_install:
  - if [ ! -f lua_install/bin/luarocks ]; then pip2 install hererocks; fi
  - if [ ! -f lua_install/bin/luarocks ]; then hererocks lua_install -r^ --$INSTALL_LUA; fi
  - export PATH=$PATH:$PWD/lua_install/bin # Add directory with all installed binaries to PATH
  - export LUA_PATH="./?.lua;$PWD/lua_install/share/lua/5.3/?.lua"
  - export LUA_CPATH="./?.so;$PWD/lua_install/lib/lua/5.3/?.so"
  - wget http://www.lua.org/ftp/lua-5.3.5.tar.gz
  - tar zxvf lua-5.3.5.tar.gz
  - cd lua-5.3.5; make $LUA_OS MYCFLAGS=-fPIC; cd ..

install:
  - if [ ! -f lua_install/bin/busted ]; then luarocks install busted; fi
  - if [ ! -f lua_install/bin/luacov ]; then luarocks install cluacov; fi
  - luarocks make # This installs necessary runtime dependencies

script:
  - lua -v
  - busted -c -o gtest -v spec/

after_success:
  - luacov "titan%-compiler" "/spec/[^/]+.lua" "titanc" && bash <(curl -s https://codecov.io/bash)
  - grep "Summary" -B1 -A1000 luacov.report.out

notifications:
  email:
    on_success: change
    on_failure: change

cache:
  directories:
    - $HOME/.luarocks
    - lua_install
